(ns sicp-clj.chapter-2.49
  (:require [sicp-clj.pict-lang.core :refer :all]))

(def x (segment->painter [(make-segment (make-vect 0.0 0.0)
                                        (make-vect 1.0 1.0))
                          (make-segment (make-vect 0.0 1.0)
                                        (make-vect 1.0 0.0))]))
(def outline (segment->painter [(make-segment (make-vect 0.0 0.0)
                                              (make-vect 0.0 1.0))
                                (make-segment (make-vect 0.0 0.0)
                                              (make-vect 1.0 0.0))
                                (make-segment (make-vect 1.0 0.0)
                                              (make-vect 1.0 1.0))
                                (make-segment (make-vect 0.0 1.0)
                                              (make-vect 1.0 1.0))]))

(def diamond (segment->painter (connect (make-vect 0.0 0.5)
                                        (make-vect 0.5 1.0)
                                        (make-vect 1.0 0.5)
                                        (make-vect 0.5 0.0)
                                        (make-vect 0.0 0.5))))

(def wave (segment->painter (concat (connect (make-vect 0.0 0.85)
                                             (make-vect 0.15 0.6)
                                             (make-vect 0.3 0.65)
                                             (make-vect 0.4 0.65)
                                             (make-vect 0.35 0.85)
                                             (make-vect 0.4 1.0))
                                    (connect (make-vect 0.6 1.0)
                                             (make-vect 0.65 0.85)
                                             (make-vect 0.6 0.65)
                                             (make-vect 0.75 0.65)
                                             (make-vect 1.0 0.35))
                                    (connect (make-vect 1.0 0.15)
                                             (make-vect 0.6 0.45)
                                             (make-vect 0.75 0.0))
                                    (connect (make-vect 0.6 0.0)
                                             (make-vect 0.5 0.3)
                                             (make-vect 0.4 0.0))
                                    (connect (make-vect 0.25 0.0)
                                             (make-vect 0.35 0.5)
                                             (make-vect 0.3 0.6)
                                             (make-vect 0.15 0.4)
                                             (make-vect 0.0 0.65)))))

(paint x)
(paint outline)
(paint diamond)
(paint wave)
