(ns sicp-clj.chapter-2.49
  (:require [sicp-clj.pict-lang.core :refer :all]))

(def draw-x (segment->painter [(make-segment (make-vect 0.0 0.0)
                                             (make-vect 1.0 1.0))
                               (make-segment (make-vect 0.0 1.0)
                                             (make-vect 1.0 0.0))]))
(def draw-outline (segment->painter [(make-segment (make-vect 0.0 0.0)
                                                   (make-vect 0.0 1.0))
                                     (make-segment (make-vect 0.0 0.0)
                                                   (make-vect 1.0 0.0))
                                     (make-segment (make-vect 1.0 0.0)
                                                   (make-vect 1.0 1.0))
                                     (make-segment (make-vect 0.0 1.0)
                                                   (make-vect 1.0 1.0))]))
(def draw-diamond (segment->painter [(make-segment (make-vect 0.0 0.5)
                                                   (make-vect 0.5 1.0))
                                     (make-segment (make-vect 0.5 1.0)
                                                   (make-vect 1.0 0.5))
                                     (make-segment (make-vect 1.0 0.5)
                                                   (make-vect 0.5 0.0))
                                     (make-segment (make-vect 0.5 0.0)
                                                   (make-vect 0.0 0.5))]))

(paint draw-x)
(paint draw-outline)
(paint draw-diamond)
